import './polyfill';
import { Sandbox } from '@cloudflare/sandbox';
// @ts-ignore - this file is generated by astro build
import astroWorker from '../dist/_worker.js/index.js';

export { Sandbox };

export default {
  fetch(request: Request, env: any, ctx: any) {
    // Handle potential double-default from re-bundling
    const worker = (astroWorker as any).default || astroWorker;
    return worker.fetch(request, env, ctx);
  }
};

